### ISSUE TITLE
Multiplatform support?

### ISSUE THREAD

**Issue by hyiltiz** [roice3/MagicTile#10]
Hi,

I just found this amazing project, and wanted to try it out. I have access to OS X and Debian Linux. Is there any way to compile and run the Magic Tile in any of these platforms?

**Comment by roice3** [comment]
Hello,

There are two options that I know of.  

(1) You can use a Windows emulator, which is what Mathologer did to run on his mac.
(2) You can use Mono to get it working on Linux.  See issue 7, where folks were doing that and discussing hurdles to make it work.

https://github.com/roice3/MagicTile/issues/7

Good luck!
