### ISSUE TITLE
Cannot run in debug env

### ISSUE THREAD

**Issue by nanma80** [roice3/MagicTile#20]
When I execute it in debug env, I see an error message upon start: Assertion failed in this line:
https://github.com/roice3/MagicTile/blob/master/MagicTile/Utils/MenuBuilder.cs#L333

I can run it in Release because this assertion doesn't fail the application there.

**Comment by roice3** [comment]
Fixed with commit d20f8c4.

I've moved away from assigning puzzle IDs manually, for situations like
this (a copy-paste issue in the {5,4} 32C puzzle).  This assert may be overly
restrictive, and maybe just needs to be removed.
