### ISSUE TITLE
No puzzles

### ISSUE THREAD

**Issue by ChristopherKing42** [roice3/MagicTile#29]
I was trying to run MagicTile on Ubuntu 16.04, and although it kind of worked, I realized it has no puzzles:

![screenshot 2018-03-28 at 8 01 45 pm](https://user-images.githubusercontent.com/8742930/38068773-2ae0e770-32d0-11e8-92d4-e5e5b0c7ed79.png)

The default puzzle works, but Tetrahedron does not load (and it says there are 0 puzzles in the bottom right).

Command line dump, in case its helpful:

```
$ xiwi -T wine MagicTile.exe 
...
Cannot open /sys/class/tty/tty0/active: No such file or directory
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:wincodecs:PngDecoder_Block_GetCount 0x166fbc0,0x33eec8: stub
fixme:wincodecs:PngDecoder_Block_GetCount 0x166fbc0,0x33eec8: stub
fixme:wincodecs:PngDecoder_Block_GetCount 0x166fbc0,0x33eec8: stub
MainForm initialized.
Missing method System.String::Format(IFormatProvider,string,object) in assembly C:\windows\mono\mono-2.0\lib\mono\4.5\mscorlib.dll, referenced in assembly Z:\home\theking\Downloads\MagicTile_3-27-18\MagicTile.exe
Menus built.
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
MainForm constructed.
fixme:win:EnumDisplayDevicesW ((null),0,0x33d180,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33d180,0x00000000), stub!
Building Puzzle...
creating underlying tiling...
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
precalculating identification isometries...
adding in cells...
analyzing topology...
marking cells for state calcs...
slicing up template tile...
adding in stickers...
setting up texture coordinates...
preparing twisting...
preparing surface data...
loading and preparing irp data...
calculating fundamental domain boundary...
Number of colors:24
Number of tiles:5000
Number of cells:4877
Number of stickers per cell:15
```

**Comment by roice3** [comment]
I'm guessing you are running the Windows version via wine? If so, that build didn't have the recent fixes, so I just pulled the latest and rebuilt ([download](http://roice3.org/magictile/downloads/MagicTile_v2.zip)).

Let me know if I'm not correct on that though. I literally just googled what wine was and made my guess based on [this stackexchange post](https://askubuntu.com/questions/31273/difference-between-wine-and-mono).

**Comment by ChristopherKing42** [comment]
I used the Mac version via wine.

**Comment by ChristopherKing42** [comment]
I also tried your download link, and it had the same issue (when used with wine). I'm going to try via mono.

**Comment by ChristopherKing42** [comment]
Peculiar, I tried the mac version using the `mono-complete` package, and it still shows `0` puzzles. Perhaps its an issue with Ubuntu 16.04?

```
mono -V
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by roice3** [comment]
I couldn’t deduce what exactly was wrong from the traced output. Curious...when did you last update mono?

**Comment by ChristopherKing42** [comment]
Rather recently, although Ubuntu usually uses old versions of packages.

**Comment by ChristopherKing42** [comment]
Although, for some reason the original Rubik's cube isn't working right (its trying to display it hyperbolically).

**Comment by roice3** [comment]
interesting, do any of the spherical puzzles work in the normal stereographic projection mode?

**Comment by ChristopherKing42** [comment]
@roice3 It does not appear so (here is what the rubik's cube looks like, btw:
![screenshot 2018-03-29 at 9 29 32 am](https://user-images.githubusercontent.com/8742930/38097892-cb0dea46-3333-11e8-8ac1-b7762ab245d8.png))

**Comment by ChristopherKing42** [comment]
Although I was able to get surface display working for spherical puzzles (but not hyperbolic ones).

**Comment by roice3** [comment]
ah, that's an OpenGL problem. The technique I use with the stencil buffer to draw concave polygons clearly isn't working, leading to a box surrounding each sticker instead.  Might be a limitation of the video card, and unfortunately, I don't think I can do anything about it.

**Comment by roice3** [comment]
It works in hemisphere disks and surface mode because that drawing is using textures (like the hyperbolic puzzles).

**Comment by ChristopherKing42** [comment]
Okay, well the hemisphere view works well enough. Is there maybe a way to detect which models are views are supported by the computer?
