### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by jhidding** [roice3/MagicTile#7]
Hi,
I saw Mathologgers video and wanted to give this program a shot under Linux/Mono.
I first tried with the binary download from the website. I'm running on Debian testing with Mono 4.2 and OpenTK 1.1.4 installed. The program gives the following messages:

```
MainForm initialized.
Menus built.
Failed to load settings.
Could not find file "/home/johannes/.config/MagicTile v2/settings.xml".
ExceptionHandler caught: Object reference not set to an instance of an object
^C
```

The window never appears. I tried compiling from source, which kind of worked (with many warnings), but the resulting binary gives the same error. I'm not a C#/.NET programmer so I'm not sure how to proceed.
Cheers!

**Comment by roice3** [comment]
Cool, you are the first I know to attempt this, so I'm not surprised at all there are problems.  Thanks for giving it a shot!

I checked the code loading the settings, which is [here](https://github.com/roice3/MagicTile/blob/master/MagicTile/Settings/Settings.cs#L68).

I'm guessing the DataContractSerializer in Mono doesn't like it if the file does not exist, even though it is perfectly happy with that in Windows.  You could try adding this line above the LoadFromXml call:

`if( !System.IO.File.Exists( StandardPaths.SettingsFile ) )
					return new Settings();`

I suspect this is the first of lots more problems though :/

**Comment by noughtmare** [comment]
Your fix seems to work, but now there is another error:
```
ExceptionHandler caught: Object reference not set to an instance of an object
```
I've debugged it and it seems this line seems to cause the error:
```
object propertyGridView = gridViewFieldInfo.GetValue( grid );
```
In `SetLabelColumnWidth` in `MainForm.cs`.

**Comment by roice3** [comment]
Yep, I think for this (and the many other issues that are bound to arise), removing any unnecessary code would be a good approach.  In this case, this function is setting the PropertyGrid columns widths to something other than the default.  In terms of getting things going in Mono, I'd just remove the call to this function myself.

**Comment by noughtmare** [comment]
Removing that call works, but now the program just exits after it reaches `Application.Run( form );`.

**Comment by noughtmare** [comment]
Here's what the `form` object looks like just before `Application.Run(form)`:
https://gist.github.com/noughtmare/a362d444180330418ec9b2f118cecf2a

PS: I don't know if this is helpful, I'm also not a C# programmer.

**Comment by roice3** [comment]
This is where I run away and hide for cover :)  Sorry.

Like I've been saying, I suspect a Mono port is going to be non trivial.

**Comment by noughtmare** [comment]
I have compiled opentk from source and added it as a .net assembly reference and now it works!

**Comment by jhidding** [comment]
I pulled from @remuladgryta fork, and this works now!

**Comment by mjg123** [comment]
This makes me very happy 👍  Are the instructions on how to build from that fork, or binaries anywhere?  I know next-to-nothing about the mono buildchain.

**Comment by jhidding** [comment]
The patch fixes some references for .NET 4.5, and the OpenTK library. I can imagine this would in turn break building it on MSVC. To build with mono, just run `xbuild` in the project root folder. The binary appears in `./MagicTile/bin/Debug`.

**Comment by mjg123** [comment]
I've compiled the opentk dependency locally, but still get "/usr/local/Cellar/mono/4.6.0.245/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'OpenTK' not resolved" (this is macos, btw) which I guess is to do with the hintpaths in here https://github.com/remuladgryta/MagicTile/blob/master/MagicTile/MagicTile.csproj#L66-L71  pointing to the wrong place?

**Comment by jhidding** [comment]
I don't have this issue since the OpenTk provided by the systems package manager in Debian works fine, but I believe setting `MONO_PATH` to the correct assemblies path should work.

**Comment by mjg123** [comment]
Ah ha!  The trick is to read the list of places that the build tools are looking for the DLLs, and just copy them into there.  Up and running now.  FWIW this is the complete set of things I had to do on MacOS:

1/ Install wine, instructions: https://www.davidbaumgold.com/tutorials/wine-mac/
2/ Clone & build opentk, instructions: https://github.com/opentk/opentk#instructions
3/ Install xbuild: `brew install mono`
4/ Clone the forked repo: https://github.com/remuladgryta/MagicTile/
5/ cd into the MagicTile repo, and try to build: `xbuild MagicTile.sln`
6/ Look for error messages in the output like: `Considered './MagicTile/R3/R3.Core/bin/Debug/OpenTK.dll' as a file, but the file does not exist`
7/ Copy the files built in step 2 into the places that xbuild is looking.  There are 2 dlls, `OpenTK.dll` and `OpenTK.GLControl.dll`.
8/ wine ./MagicTile/bin/Debug/MagicTile.exe
9/ ... 🎉  MAGIC 🎉

**Comment by noughtmare** [comment]
@mjg123 if you install mono you shouldn't have to install wine, you could probably just run `mono ./MagicTile/bin/Debug/MagicTile.exe` in step 8.

**Comment by mjg123** [comment]
That doesn't quite work :(

```
MagicTile|master⚡ ⇒ mono MagicTile/bin/Debug/MagicTile.exe
WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all
ExceptionHandler caught: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception.
Inner exception was: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception.
```

**Comment by noughtmare** [comment]
Maybe you have to install a 32bit version of mono, I think that is included in wine so that's probably easier.

**Comment by roice3** [comment]
This is great, you guys are awesome.

Now I'm wondering if we should try to get a decent Release build for Mono and include it as an additional download on the site.  I've had a lot of folks ask about running MagicTile on Mac over the years, and it'd be cool to provide them a path (other than telling them to run an emulated Windows machine).

**Comment by remuladgryta** [comment]
I tried compiling MagicTile on a whim after seeing the mathologer video. I'm not very experienced with C# development, but it only took a couple of hours to get working. It's nice to see someone appreciate it!

To get it to build, all I really did was open the project in monodevelop, change the target framework in the project settings to one of the available ones. The majority of the time I spent was on googling C# syntax in order to track down the PropertyGrid issue and just disable the method.

I don't have access to a mac so I can't test it, but I would guess that using the osx version of monodevelop to fix the build dependencies is all that's needed to get my fork working on mac.

**Comment by hyiltiz** [comment]
This is exciting! Once OSX is running, Linux is just one step away! I'll try the above method, and see if I can let it work in my OSX and Linux (Debian).

**Comment by cpeosphoros** [comment]
Hi there, sorry for necroing an old issue (though it's still open) and also if my suggestions seems a bit naive.

That said, wouldn't it be simpler to just provide a pre-made version of settings.xml and copying it into .config/MagicTile v2 ?

Then you could just run $wine MagicTile.exe (in a winetricked box with all needed dependencies)

**Comment by roice3** [comment]
I'd be happy to include this if someone sends me a pull request with said settings.xml file and updates to the readme file with instructions.  I am not sure if there are code changes that would be required as well.  Based on some of the comments above, it seems that might be required.

**Comment by Immchuck** [comment]
I am new to this whole coding thing.. I really don't know much. I am 12 years old but i do plan on learning Javascript and such one day. I just want to know if any of you have made something work for this. What your saying is not entirely easy to understand for someone like me so i was wondering if you could just guide me through and let me know if you figured something out.. I have mac so i cant use magictile and as i love rubiks cubes in general, i would love to try this.
Thanks

**Comment by roice3** [comment]
@Immchuck, my wife recently got a mac so using it and the information in this thread, I was able to get a build created and uploaded.  I've put the mac download and instructions here:

http://roice3.org/magictile/downloads/mac.htm

It may not work perfectly, but I hope it gets you going.

**Comment by cpeosphoros** [comment]
Just leaving a reference to #26

**Comment by Immchuck** [comment]
I have no idea what this means, hoping you can help
![screen shot 2018-03-29 at 10 06 45 pm](https://user-images.githubusercontent.com/37758535/38122913-b3708aaa-339d-11e8-97ea-238c5a027200.png)

**Comment by cpeosphoros** [comment]
MagicTile.exe

names are case sensitive

**Comment by Immchuck** [comment]
I can always trust you!

**Comment by Immchuck** [comment]
What! It still says the same thing!

**Comment by roice3** [comment]
@Immchuck, it’s hard to tell but it looks like you are not running the correct command to get to the directory where MagicTile lives. You don’t want to “cd: MagicTile.exe”. You want to “cd DirectoryPath”. DirectoryPath is where you uncompressed the download. 

If you still have issues, please provide details about where you decompressed the file and the exact sequence of Terminals commands you are calling. That will help diagnose.

**Comment by Immchuck** [comment]
Ok. Ill try that. I appreciate you working with me while i am being very problematic.

**Comment by Immchuck** [comment]
So i unzipped my MagicTile folder in my downloads and so i have it and so i put in the command
"cd /Users/Steve-----/Downloads" and so i'm in my downloads folder, then i type the command
"mono --arch=32 MagicTile.exe" And it still says no such file or directory. (The dashes in the cd command is really just me censoring my name so thats nothing i typed in the actual name)

**Comment by Immchuck** [comment]
Great! I will try this. Will i have to repeat these steps each time I open it? I appreciate you doing this for me, roice!

**Comment by Immchuck** [comment]
I did it! Yaaaay! Hopefully i will no longer have to bother you now!

**Comment by roice3** [comment]
Sweet, glad you got it working. And thank you for making the request. Feels good to finally support Mac and I needed an extra kick to provide better support.

As for your question about repeating the steps... you do have to run it from Terminals each time, but there are ways to make that more convenient. A google search showed there may be a nice way to do it with [applescript](https://superuser.com/questions/16750/how-can-i-run-an-application-with-command-line-arguments-in-mac-os). Another option would be to make a bash script, but it'd probably be about as much effort to run the script as to just run the program.

In any case, have fun with the puzzles!

**Comment by Immchuck** [comment]
Magictile is doing great! It's really fun. One Question: Would this work with any other .exe files i cannot open can i just replace 'MagicTile.exe' With something else or would that take extra commitment?

**Comment by roice3** [comment]
Hi @Immchuck, glad to hear that!

Unfortunately, Mono doesn't work on arbitrary .exe files. They have to be specially built so the answer to your question is 'nope'.

To run other Windows programs, your easiest option may be an emulator like [Parallels](https://www.parallels.com/products/desktop/), though that costs money. You can also look into [Wine](https://www.winehq.org/).

**Comment by Immchuck** [comment]
Uhh so i got a new pc and all that work was for nothing lol

**Comment by roice3** [comment]
@Immchuck, not for nothing! I've been wanting to support Macs for a long time and I'm sure there are others who appreciate you pushing me across the finish line :)
