### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by whentze** [roice3/MagicTile#8]
There seems to be no license for MagicTile, which means people need explicit private permission from the author to even use MagicTile without infringing on the copyright. Is this intended?

See http://choosealicense.com/no-license/ for what it means to host code on GitHub with no license, and the problems it causes.

**Comment by roice3** [comment]
oops, thanks!  I want to be as simple and permissive as possible.  Just added the MIT license, which hopefully does that.

Cheers,
Roice
